apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBwvIZ+f6UGC3F+8u0q5IuSBJQH750GbYKvj0Cb4UeobS/CzXtcfjvqmfnzC1oZpUjeSXwS3s5wUqZT0SJ+UdoSzHElN5vuRNswcj18hqG/p70qPvPwlKrImBSmVjKIGle2pA3mDuukWiG9OolQh5N9xaRptEaveZ8JZ+Xxg2uiR55TNzVCpLFZZFO5D77V8gvDwGWUoRXa2QljS0o8vCNVsDEpvVPXmr3xvva0Xm40h666sIAX18wDSK970gwSrIDeY4lQZyj8rTb176INcBDqrTPJsaKpXUGqqJpXmAfZ9H1FdZM81ndkKvelmQMooxgOoRXMlMpOVkxF9UWVBOTumD64S3B0gaMeXiifOnOis6DO3VnERGDCotaLS82lsqtclZUzEt9mh5XBCz0xDARFLriiU8uDjsCa8PE4gBybXwqe2K1WqEANo5Uel0JYRAKzhyPdgXtT9ERVSfwCmwJjAKVEfIQZmqtCOtJz++1Rvhr8X9XYygdaPanZ5B5NNkk9iGxlqV5hlWVRkOiQl/mb+a7+8s9hLzylD/EatGMlb9bn6DBgrHhjV0sdTTQoZ4CtITzOOPx5W9uLvZflNBzZFlW5VcXwi38d17QxpGXQI+rnAX3IompAoOT1ZRYOk1D1sU7EcGyDnlRKEuTBIIvl4iGHC4quKnSxhsX50N/dzrPeE59JdTbcptfTndgNue670nvhLfoaGfBvsJaBXN+VNf6ovI6Ib1G7X4AUku/sWo9kXIqoWw==
    ARTIFACTORY_PASSWORD: AgBGeErru6VqnwxJBq2Y7i3VGMuTqbXGWrJajRho3PunozV8nWxKREauGioDod1/igtvk764K4YQSOxdItBeKnctqNNTr/OLFZ1iCAkpgt7oxtLzBxHzW3JTX51N2+0DjrlOIeIfkN5XXGcbla3LskeqiQx6hmscCuO1iX+APFDy+8ExsuF6ggBcJV9pJRoJiDzyG3QtaXPaweeV4WT/7fP/Z0swevVN5PQNt8FtHqqejjX0Wvg2vfAScrJrdWP+lNGft/DlxwGTQZwr5+QeDyabsKFmQlhYIgxPeX57h/8RDUDBJD5K+rYnYt1lyUINdJrpomoIrBubhc5m5pAeijHEtGZwkUpDIGP81iW1w7jB6Zlih0zOPqKWf4Xl88yX7J4dABe6oghj+UrXXfnCT6AoUGsLya1aA4MRqqyPN+trDYmR6dJmG/kUfDS4zHWFokQbBOhyQiRurrFVnW82CbkhP7VRK1Hb2/PEKUkJm262OOTYdP1Kn5gFUvBBM7+eBaZz1cLRDQp1r74ciIhKQTDBPk5eHgT/Wdkek2Y10u4k6GW81sSflOI5CIUovVdMhtiI1ne5NG393EdodC2PTp6rgSAOq3+hGWHpCzM0wa2tYmqHaObSirQ+9k8snPIt7eeTfpZWPnLB3KegM3c1CVGAU3lzicyWHce+4cRyo7uLNvSYLpHU2LAOmsUqwSY1OxmRSQex69MjhSSW8Yd0PKysPLXjdA==
    ARTIFACTORY_URL: AgAZIWd33J7OHesmYelZ7jKt68r6AC2U+CLKa9eODGPesZ/mMUn8lWB+l9og5swSL4nOIvBcMdy/jY77YniE1oapSc2Odt+HTyP9QBkzIN9RyaCKRMHuMOjpBcoFYtwSF1dL3nsLOeKfuHQsWraO/MuW8XevJwP17QeykLLBDOljdieWXMNZHorbtc3eToph2kBUZET1HHFmu7Fe077ByKDlLowIhd2oZAXjLSgIy9z/EDZfodVdrfrFGzKbnpzEo1caX2BBtZuz6Pywjd3QkI1pIQq9Oxhiih0QAHK6UcLur4zvmmmAap9mkWJeXLtEC9HB/iS0eDl7q2rDaDGXdWLQ1mPJSV2ipLGjCAJErRZ6nAViopqyizA9kTXX/Kx0lcUUHUS9zXwy4soeHGdJqfXE27tvS9j3V6KxTTBIF2WflLg5xC9iNSbHRHoIAgJSIQBwcgj7UaTnZ2UwIrhjqXmw/KwKt+XRLivIoQI0gV62UnWZNEr3RA2KM+S2DVFfQkYSt6V3LYcT/QaieWd0FTdSQA/MZRHCcP7rCyDFjjGaMtGqO4LUSzUbmYTchlUT7ac37UVCKEo7hyBCESrUK8tZe1a3ToHcUqcEuxlbbvLYWsj5lGct+WvGVlQ6T1t2HL4caSz/XIZfcGN1iakQSYEpzM8wUk0uZa9iNMj7tDCPEyVeSGxm4NH9Gz0Z1djAff3KSqLjYSmysy/6Z746L1+g4w7m0qpUIP7AnPKu8cKLeZOqyvkkpzMPxQ==
    ARTIFACTORY_USER: AgAtVq+AMH+Sg9+d3BXYMNH9qK7ZfucMVbz3Jhut2K5ReGW4/eKLC1BgHtjipdi1Vx0gZqV8joPom7iM8tf6J+fJSUKwamOOAJ9w0W+3ba+NZ2/87jKbU76OXHbrbyJHm75fP/0vy0gEfoBot3dRIX0Q5t/gGCeMyjMly4wvjF6EQZJF1oxs2e4lW9pNgg7S3ZZN5PXoMHjtUeFfwzhKIldLYGf3/O5i8IuuGVsRuBBiCOMz4w6HaU4u+LJ6LjHs3K6M9lN5x53sGPu4h1Fbh9Ch96DBIBdCjGcOm5hSwpIcWGCb3kCDbdSe3Adm+Zu9IvpumTmac8Em4QYeNcsyo3ohZgUhpn0rNZNBwQJ/VRePSgF4I4NHluLO9h+/QAiauUGD7zEvKuGBye0QVlg15cI6UECRb0Aw0Ro6PcZf8XGwOyCJSGQasi37g7sbSi9RyFeBZJg1dmM7slpdqwBXemRT8711nykEz5cA2+z7hQ8c++cFS6241yWOTsVrxhAfXeHqNw3wbkZ1QD1LoCCXTQRQJZ3520FjXOT4dyqX3ymAHlpKPCQSDsgYQfJy76eTlI8Y4WQRmCzacL9xUZsIAg3wnYEUHfRLLGynNYKllM7GSL99XyrWT3PKhZFpYUlbDJ+GCpX54eNcD99bUiuQaceu7PVNfxovFKJYXhxqinYWm86rgg69aQyjIBXfNOC1soukpYYovQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-09-03T15:33:01Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-09-03T15:34:41Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

