apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBNRXQBa0aejxAr3twEZFQPJEiqRRHDAfjRUeiplF1dv7sZBG41W3tM/q7LiymFMi6GZrxKLAtlap1A6Iafh4TMgln2MhhpDQAa3oWMD57y5gXpGfHWKa/vOGqvH3f7eJb0hpXepddGBSFXBaT66RTF4rhDPxhGDQbV3ZgI+StsRC4cJKTZVMR81KAaIbkg6+PqhFP/M1+tOVJVdu1Ng22dDCCA11s8icdb0ZMe+ImJJohvWGIY2Z14PKARZrkucWj9k6C3bx2H+hPgqsszoW2p3mb6lSyhZvPwAG7JiCoM0Ui7ymDSEFNh2HweSZIPOhLQ3VY0x8RIgQpUv3da958/zw85nATeZtjxVtHnIF5+umL63rvt2aX3Cq1slttyz8SSGSWLXxzZvOUOie/ieHOutQoYC3a1kjyFu9gHRJ5R6iHpQPztl+OHQzku9YcajCwnWb9w71M/7hDpoG2n0G7w+BB5g0JUMoNP6VvYFgh+kWHgpw/ch2LeJRYofYcvJq0wsQf8Uv1fGl6Ffwy0cmjSmzkQvjkPsPiCYs3Z2Cqaa/WAsvIj8pAPRsrY9oJOZe1J9rJga10UaQ1y6841BhfLSfgMvCEI6dtCleg1vB0EsKqHZQsOwgcYSA+5l1VLPnpt4IC4143dmRdSxjceCAY7JNEZB4USSSoY5+U7dpwwOlYkRa5z/lPJVv0EPPEM92HU8CMHnE8Y9DcyI50oUDIs7+qJk/sejViNERz4gbbXlsCebSiRfm+b
    username: AgCvdhjzkwSr9qySj3OYs/uscsoMnNwDOJjdoNGLjQWcHuyNQYfbU8ik3FJLqfBa4y154ENj3naSj/ILitqREhFNSjLFb4C8HgbZw5ugtaFV+LCf7uPUvE7PhDVkBVOlV2eu5PDpSDA/Nl2TFnZvy2Sw3jrorSUH6RIPmX37PcnVCvu2DYuEs/0kYNzFu5lSmMF+yFtJZ9L92/Tj3LmAn17ZfX8dQ+GiWCc/v/oFxg9k+qa9kKoMQa2vg7qtODNlNW9x5q2SP/lkN0YCz/HQpa08ebmpR2HslF+Qd9Fzu+TmP6czZH3uJYemjvXVrzsvaURbVb986WAXIu2GvTV7TVzeO5sgNVfkvcW0eQ05jj/KCNRUd8PmFMlnGENWQSMoWXLlFB0XMEnoaVbjlNK126Vywkx8Iz2hJFAM9hV7nGFULU5HMA3xckvA529XoWLud9YEKe6X5GAHyN2i/nSToEwdqNmHFsNVd9Ihyd8YUTdReH7GjfG4TbbD5BHnwGxKkwfEd5xe6H7aJ/DMAJuxaZarFUb+mE4mcZbn5YcEO8CQJb3WXk3lb/LBm8Iz+xfxeJrr00IwcXyo1YN8AAdQrWQmnQqLbe9SbtzSWvwMX3FNomUXNHVt4U78q3D8oIJO6/xKF5/af2cRWA0e7jM+zWsZmyElqffQkdnyY8LF/XUPrx4YweKfP5MC7SPwOhSDvbCuiUJ+a4pp
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

